### PR TITLE
Fix typo in ai-friendly-naming-convention.md

### PR DESCRIPTION
**Pull request by ohbarye**
This pull request just fixed the typo.

### CODE REVIEW

**Review by yuhattor — APPROVED** [review]
Thank you for the PR (and sorry for being late to review this PR..)

**Comment by ohbarye** [comment]
I found the page has already been deleted, so I'm closing this pull request. But thanks for your review, anyway!

**Comment by yuhattor** [comment]
Thank you for your contribution!!
I actually didn't remove the contents, but archived...　Sorry for the slight delay, but I have incorporated the content as a Co-author! Thanks again!

https://github.com/yuhattor/copilot-patterns/commit/49e2c2f4741873ae0a8c185b98da06442523bf23

**Comment by ohbarye** [comment]
Oh, I wasn't aware of the archived content. And I really thank you for your incorporation!

**Comment by yuhattor** [comment]
My pleasure! Thank YOU!!!

**Pull request closed without merging**
